import Questionnaire2
import ArtistRec2
#Terminal versions provide the same functionality, so there's no need for a modified duplicate
from terminal_version import PlaylistRec
from terminal_version import AccountRec
import GeminiConnect
import SpotifyConnect
import os

#Flask stuff to connect to the front-end
from flask import Flask, jsonify, request
from flask_cors import CORS

app=Flask(__name__)
CORS(app)

#Initialize SpotifyConnect object
my_spotify = SpotifyConnect.SpotifyConnect()


#@param String:prompt
#@return String: GeminiConnect.generate_playlist
#Used to fetch the playlist generated by Gemini API 
def use_gemini(prompt):
    return GeminiConnect.generate_playlist(prompt)

#@param String: song_list
#Used to parse through the Gemini generated string of songs to create an array of songs
#specifying title, artist, and year. Afterwards, use Spotify API to search for the songs
#and generate a playlist on the account.
def use_spotify(song_list,my_spotify):
    songs=[]
    for line in song_list.strip().split('\n'):
        print("line is", line)
        title, rest = line.split(' /// ')
        album, rest = rest.split(' ### ')
        artist, year = rest.split(' (')
        year = year.rstrip(')')
        songs.append({'artist': artist, "title": title, "album":album, "year": year})
    
    my_spotify.search_songs(songs)
   
#Allows the user to perform a "logout" by just deleting the .cache file, and restarting the program    
def logout_user():
    dir_path=os.getcwd()
    cache_path=dir_path+"/src/backend/.cache"
    #delete .cache file
    os.remove(cache_path)
 
#JSON function to meant to receive user input questionnaire data
# from the front end, then generate a prompt, and then use Gemini 
# and Spotify.
#@param Dictionary: data   
@app.route('/use-questionnaire', methods=['POST'])
def use_questionnaire():
    input_data = request.json.get('data')
    prompt = Questionnaire2.questionnaire(input_data)
    
    response = use_gemini(prompt)
    print(response)
    
    use_spotify(response,my_spotify)
    
    return jsonify(response)
#JSON function to meant to receive user input playlist data
# from the front end, then generate a prompt, and then use Gemini 
# and Spotify.
#@param String: playlist_name   
@app.route('/use-playlist', methods=['POST'])
def use_playlist():
    playlist_name = request.json.get('playlist_name')
    prompt=PlaylistRec.playlist_rec()
    
    response = use_gemini(prompt)
    print(response)
    
    use_spotify(response,my_spotify)
    
    return jsonify(response)
#JSON function to meant to simply send back the results of the prompt.
#The artist data is gathered in from Spotify without needing specific input
#from the front-end.
@app.route('/use-account', methods=['POST'])
def use_account():
    
    top_artists=my_spotify.get_user_top_artists()
        
    prompt=AccountRec.account_rec(top_artists)
    
    response = use_gemini(prompt)
    print(response)
    
    use_spotify(response,my_spotify)
    
    return jsonify(response)

#JSON function to meant to receive user input questionnaire data
# from the front end, then generate a prompt, and then use Gemini 
# and Spotify.
#@param Dictionary: inputData   
@app.route('/use-artist', methods=['POST'])
def use_artist():
    artist_name = request.json.get('artist')
    prompt=ArtistRec2.artist_rec(artist_name)
    
    response = use_gemini(prompt)
    print(response)
    
    use_spotify(response,my_spotify)
    
    return jsonify(response)
    
if __name__ == '__main__':
    app.run(debug=True,port=5000)
    
